// src/app/dashboard/page.tsx or src/pages/dashboard.tsx
'use client'
import { Component, useState } from 'react';
// import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import '../globals.css';
import { Theme, SegmentedControl } from '@radix-ui/themes';
import PopoverComponent from '@/components/popover';
import ThemeToggle from '@/components/themeToggle';
import ScrollBar from '@/components/scrollBar';
import NavigationMenuDemo from '@/components/navMenu';
import AlertDialogDemo from '@/components/alertDialog';
import EditDialog from '@/components/editDialog';
import { AccordionShad } from '@/components/accordianShad';
import {ButtonComponent} from '@/components/buttons';

const components: any = {
  'Component 1': {
    placeHolder: 'Popover & comment',
    Component: <PopoverComponent />
  },
  'Component 2': {
    placeHolder: 'Scroll Bar',
    Component: <ScrollBar />,
  },
  'Component 3': {
    placeHolder: 'Nav menu Primitive',
    Component: <NavigationMenuDemo />
  },
  'Component 4': {
    placeHolder: 'Edit Dialog',
    Component: <EditDialog />
  },
  "Component 5": {
    placeHolder: 'Accordion ShadCN',
    Component: <AccordionShad />
  },
  'Component 6': {
    placeHolder: 'ShadCN Button',
    Component: <ButtonComponent />
  },
  // Add more components here
};

export default function Dashboard() {
  const [selectedComponent, setSelectedComponent] = useState<string | null>(null);

  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold mb-4">Dashboard</h1>
      <header className="absolute top-4 right-4">
        <ThemeToggle />
      </header>
      <SegmentedControl.Root defaultValue="Component 1">
        {Object.entries(components).map(([key, { placeHolder, Component }]) => (
          <SegmentedControl.Item
            value={key}
            onClick={() => {
              console.log(placeHolder);
              setSelectedComponent(key);
            }}
          >
            {placeHolder}
          </SegmentedControl.Item>
        ))}
      </SegmentedControl.Root>
      <div className="mt-8">
        {selectedComponent ? (
          <div className="p-4 border border-gray-300 rounded">
            {components[selectedComponent].Component}
          </div>
        ) : <PopoverComponent />}
      </div>
      <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor malesuada felis, ut euismod nulla dictum nec. Proin lacinia metus vitae felis ullamcorper, nec dapibus lacus ultricies. Morbi vehicula turpis eu augue consectetur, at ultricies orci sollicitudin. Nullam a justo non turpis vestibulum eleifend at et dui. Curabitur malesuada nibh a ante fringilla, non cursus nisl vehicula. Ut at lacus elit. Etiam id urna a urna ultricies posuere. Suspendisse vehicula urna vel enim blandit, sed ullamcorper eros faucibus. Donec sollicitudin, sapien in interdum venenatis, tortor justo malesuada justo, sed tincidunt dolor odio et nunc. Vivamus in suscipit nulla. Donec at arcu vitae nulla bibendum varius. Vestibulum vel vehicula nisl. Phasellus at urna vel purus vestibulum vulputate. Integer accumsan orci eu metus fermentum, vel consectetur lectus bibendum. Nulla vel lacus in libero vehicula blandit id a sapien.</p>

        <p>Mauris luctus metus ac ligula consequat, at iaculis risus volutpat. Aliquam convallis magna at ex interdum, ac tempor nulla interdum. Nullam lacinia ex a lacus blandit, vel luctus magna pellentesque. Vestibulum vitae lacinia mi. Fusce rutrum ligula non elit porttitor, id scelerisque lacus dignissim. Nulla facilisi. Sed non velit nec nisl dignissim feugiat in non felis. Nullam at erat vel libero gravida viverra. Proin accumsan sapien nec sapien pharetra lacinia. Vestibulum in nisi auctor, ultricies justo vel, luctus libero. Nam ut dapibus leo. Cras dapibus, lacus sed pharetra vehicula, sem purus egestas lacus, ac interdum augue ipsum a justo. Sed vitae justo non nisl varius egestas.</p>

        <p>Quisque ut justo a dolor auctor fermentum. Nam auctor felis non neque facilisis, id fringilla dolor feugiat. Sed in justo vel nulla dapibus gravida. Curabitur auctor turpis sit amet arcu sodales, nec dignissim velit gravida. Nam non sem sem. In hac habitasse platea dictumst. In interdum velit eget sapien pharetra, a tempor erat egestas. Maecenas non felis sit amet justo pretium blandit. Phasellus in vestibulum nulla, eget sollicitudin odio. Vivamus tristique libero sit amet massa condimentum, ac scelerisque dolor fermentum. Nunc id arcu nec lectus tincidunt dictum. Vestibulum vel sem vel nunc hendrerit fermentum. Pellentesque at nisl leo. Quisque accumsan ex in ultricies venenatis. Curabitur aliquam quam a enim efficitur, in eleifend turpis tristique.</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer nec libero nec justo tempor tincidunt. Aenean dignissim leo eget dui malesuada, id euismod odio sodales. Cras in libero eu ex pellentesque egestas. Nunc vehicula, mauris ac egestas faucibus, metus metus malesuada urna, non volutpat ex libero nec risus. Phasellus eu purus ut lorem tincidunt porttitor at sit amet sem. Fusce at tortor dignissim, pharetra urna vel, fermentum mauris. In dapibus magna sit amet urna viverra, vel viverra sem luctus. Donec id velit nec odio sodales euismod. In bibendum ligula sit amet eros aliquet, quis fermentum dui tincidunt. Curabitur at justo vitae libero malesuada aliquet.</p>

        <p>Mauris ut neque sed nisl laoreet pharetra. Vivamus malesuada lacus nec magna vehicula, nec posuere elit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus augue non feugiat efficitur. Cras laoreet orci nec tortor ultricies, in luctus turpis scelerisque. Etiam gravida elit a justo dictum, et convallis ligula facilisis. Nulla vestibulum enim ut elit suscipit, in consectetur eros facilisis. Nulla dapibus mauris sed mi lobortis, in congue justo vestibulum. Donec scelerisque, augue sit amet varius dignissim, nisi dolor tempus orci, ac posuere mauris turpis id justo. Nam eu eros at lorem rhoncus tincidunt. Donec interdum, libero at viverra lobortis, lacus felis sagittis risus, vel cursus quam sapien ac nunc. Duis feugiat, sapien eu tempor vehicula, tortor elit dignissim turpis, sit amet pretium sapien purus eu ex. Ut facilisis consectetur augue, ut vulputate felis egestas vel. Suspendisse condimentum malesuada dui nec feugiat. Aliquam erat volutpat.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor malesuada felis, ut euismod nulla dictum nec. Proin lacinia metus vitae felis ullamcorper, nec dapibus lacus ultricies. Morbi vehicula turpis eu augue consectetur, at ultricies orci sollicitudin. Nullam a justo non turpis vestibulum eleifend at et dui. Curabitur malesuada nibh a ante fringilla, non cursus nisl vehicula. Ut at lacus elit. Etiam id urna a urna ultricies posuere. Suspendisse vehicula urna vel enim blandit, sed ullamcorper eros faucibus. Donec sollicitudin, sapien in interdum venenatis, tortor justo malesuada justo, sed tincidunt dolor odio et nunc. Vivamus in suscipit nulla. Donec at arcu vitae nulla bibendum varius. Vestibulum vel vehicula nisl. Phasellus at urna vel purus vestibulum vulputate. Integer accumsan orci eu metus fermentum, vel consectetur lectus bibendum. Nulla vel lacus in libero vehicula blandit id a sapien.</p>

        <p>Mauris luctus metus ac ligula consequat, at iaculis risus volutpat. Aliquam convallis magna at ex interdum, ac tempor nulla interdum. Nullam lacinia ex a lacus blandit, vel luctus magna pellentesque. Vestibulum vitae lacinia mi. Fusce rutrum ligula non elit porttitor, id scelerisque lacus dignissim. Nulla facilisi. Sed non velit nec nisl dignissim feugiat in non felis. Nullam at erat vel libero gravida viverra. Proin accumsan sapien nec sapien pharetra lacinia. Vestibulum in nisi auctor, ultricies justo vel, luctus libero. Nam ut dapibus leo. Cras dapibus, lacus sed pharetra vehicula, sem purus egestas lacus, ac interdum augue ipsum a justo. Sed vitae justo non nisl varius egestas.</p>

        <p>Quisque ut justo a dolor auctor fermentum. Nam auctor felis non neque facilisis, id fringilla dolor feugiat. Sed in justo vel nulla dapibus gravida. Curabitur auctor turpis sit amet arcu sodales, nec dignissim velit gravida. Nam non sem sem. In hac habitasse platea dictumst. In interdum velit eget sapien pharetra, a tempor erat egestas. Maecenas non felis sit amet justo pretium blandit. Phasellus in vestibulum nulla, eget sollicitudin odio. Vivamus tristique libero sit amet massa condimentum, ac scelerisque dolor fermentum. Nunc id arcu nec lectus tincidunt dictum. Vestibulum vel sem vel nunc hendrerit fermentum. Pellentesque at nisl leo. Quisque accumsan ex in ultricies venenatis. Curabitur aliquam quam a enim efficitur, in eleifend turpis tristique.</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer nec libero nec justo tempor tincidunt. Aenean dignissim leo eget dui malesuada, id euismod odio sodales. Cras in libero eu ex pellentesque egestas. Nunc vehicula, mauris ac egestas faucibus, metus metus malesuada urna, non volutpat ex libero nec risus. Phasellus eu purus ut lorem tincidunt porttitor at sit amet sem. Fusce at tortor dignissim, pharetra urna vel, fermentum mauris. In dapibus magna sit amet urna viverra, vel viverra sem luctus. Donec id velit nec odio sodales euismod. In bibendum ligula sit amet eros aliquet, quis fermentum dui tincidunt. Curabitur at justo vitae libero malesuada aliquet.</p>

        <p>Mauris ut neque sed nisl laoreet pharetra. Vivamus malesuada lacus nec magna vehicula, nec posuere elit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus augue non feugiat efficitur. Cras laoreet orci nec tortor ultricies, in luctus turpis scelerisque. Etiam gravida elit a justo dictum, et convallis ligula facilisis. Nulla vestibulum enim ut elit suscipit, in consectetur eros facilisis. Nulla dapibus mauris sed mi lobortis, in congue justo vestibulum. Donec scelerisque, augue sit amet varius dignissim, nisi dolor tempus orci, ac posuere mauris turpis id justo. Nam eu eros at lorem rhoncus tincidunt. Donec interdum, libero at viverra lobortis, lacus felis sagittis risus, vel cursus quam sapien ac nunc. Duis feugiat, sapien eu tempor vehicula, tortor elit dignissim turpis, sit amet pretium sapien purus eu ex. Ut facilisis consectetur augue, ut vulputate felis egestas vel. Suspendisse condimentum malesuada dui nec feugiat. Aliquam erat volutpat.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor malesuada felis, ut euismod nulla dictum nec. Proin lacinia metus vitae felis ullamcorper, nec dapibus lacus ultricies. Morbi vehicula turpis eu augue consectetur, at ultricies orci sollicitudin. Nullam a justo non turpis vestibulum eleifend at et dui. Curabitur malesuada nibh a ante fringilla, non cursus nisl vehicula. Ut at lacus elit. Etiam id urna a urna ultricies posuere. Suspendisse vehicula urna vel enim blandit, sed ullamcorper eros faucibus. Donec sollicitudin, sapien in interdum venenatis, tortor justo malesuada justo, sed tincidunt dolor odio et nunc. Vivamus in suscipit nulla. Donec at arcu vitae nulla bibendum varius. Vestibulum vel vehicula nisl. Phasellus at urna vel purus vestibulum vulputate. Integer accumsan orci eu metus fermentum, vel consectetur lectus bibendum. Nulla vel lacus in libero vehicula blandit id a sapien.</p>

        <p>Mauris luctus metus ac ligula consequat, at iaculis risus volutpat. Aliquam convallis magna at ex interdum, ac tempor nulla interdum. Nullam lacinia ex a lacus blandit, vel luctus magna pellentesque. Vestibulum vitae lacinia mi. Fusce rutrum ligula non elit porttitor, id scelerisque lacus dignissim. Nulla facilisi. Sed non velit nec nisl dignissim feugiat in non felis. Nullam at erat vel libero gravida viverra. Proin accumsan sapien nec sapien pharetra lacinia. Vestibulum in nisi auctor, ultricies justo vel, luctus libero. Nam ut dapibus leo. Cras dapibus, lacus sed pharetra vehicula, sem purus egestas lacus, ac interdum augue ipsum a justo. Sed vitae justo non nisl varius egestas.</p>

        <p>Quisque ut justo a dolor auctor fermentum. Nam auctor felis non neque facilisis, id fringilla dolor feugiat. Sed in justo vel nulla dapibus gravida. Curabitur auctor turpis sit amet arcu sodales, nec dignissim velit gravida. Nam non sem sem. In hac habitasse platea dictumst. In interdum velit eget sapien pharetra, a tempor erat egestas. Maecenas non felis sit amet justo pretium blandit. Phasellus in vestibulum nulla, eget sollicitudin odio. Vivamus tristique libero sit amet massa condimentum, ac scelerisque dolor fermentum. Nunc id arcu nec lectus tincidunt dictum. Vestibulum vel sem vel nunc hendrerit fermentum. Pellentesque at nisl leo. Quisque accumsan ex in ultricies venenatis. Curabitur aliquam quam a enim efficitur, in eleifend turpis tristique.</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer nec libero nec justo tempor tincidunt. Aenean dignissim leo eget dui malesuada, id euismod odio sodales. Cras in libero eu ex pellentesque egestas. Nunc vehicula, mauris ac egestas faucibus, metus metus malesuada urna, non volutpat ex libero nec risus. Phasellus eu purus ut lorem tincidunt porttitor at sit amet sem. Fusce at tortor dignissim, pharetra urna vel, fermentum mauris. In dapibus magna sit amet urna viverra, vel viverra sem luctus. Donec id velit nec odio sodales euismod. In bibendum ligula sit amet eros aliquet, quis fermentum dui tincidunt. Curabitur at justo vitae libero malesuada aliquet.</p>

        <p>Mauris ut neque sed nisl laoreet pharetra. Vivamus malesuada lacus nec magna vehicula, nec posuere elit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus augue non feugiat efficitur. Cras laoreet orci nec tortor ultricies, in luctus turpis scelerisque. Etiam gravida elit a justo dictum, et convallis ligula facilisis. Nulla vestibulum enim ut elit suscipit, in consectetur eros facilisis. Nulla dapibus mauris sed mi lobortis, in congue justo vestibulum. Donec scelerisque, augue sit amet varius dignissim, nisi dolor tempus orci, ac posuere mauris turpis id justo. Nam eu eros at lorem rhoncus tincidunt. Donec interdum, libero at viverra lobortis, lacus felis sagittis risus, vel cursus quam sapien ac nunc. Duis feugiat, sapien eu tempor vehicula, tortor elit dignissim turpis, sit amet pretium sapien purus eu ex. Ut facilisis consectetur augue, ut vulputate felis egestas vel. Suspendisse condimentum malesuada dui nec feugiat. Aliquam erat volutpat.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor malesuada felis, ut euismod nulla dictum nec. Proin lacinia metus vitae felis ullamcorper, nec dapibus lacus ultricies. Morbi vehicula turpis eu augue consectetur, at ultricies orci sollicitudin. Nullam a justo non turpis vestibulum eleifend at et dui. Curabitur malesuada nibh a ante fringilla, non cursus nisl vehicula. Ut at lacus elit. Etiam id urna a urna ultricies posuere. Suspendisse vehicula urna vel enim blandit, sed ullamcorper eros faucibus. Donec sollicitudin, sapien in interdum venenatis, tortor justo malesuada justo, sed tincidunt dolor odio et nunc. Vivamus in suscipit nulla. Donec at arcu vitae nulla bibendum varius. Vestibulum vel vehicula nisl. Phasellus at urna vel purus vestibulum vulputate. Integer accumsan orci eu metus fermentum, vel consectetur lectus bibendum. Nulla vel lacus in libero vehicula blandit id a sapien.</p>

        <p>Mauris luctus metus ac ligula consequat, at iaculis risus volutpat. Aliquam convallis magna at ex interdum, ac tempor nulla interdum. Nullam lacinia ex a lacus blandit, vel luctus magna pellentesque. Vestibulum vitae lacinia mi. Fusce rutrum ligula non elit porttitor, id scelerisque lacus dignissim. Nulla facilisi. Sed non velit nec nisl dignissim feugiat in non felis. Nullam at erat vel libero gravida viverra. Proin accumsan sapien nec sapien pharetra lacinia. Vestibulum in nisi auctor, ultricies justo vel, luctus libero. Nam ut dapibus leo. Cras dapibus, lacus sed pharetra vehicula, sem purus egestas lacus, ac interdum augue ipsum a justo. Sed vitae justo non nisl varius egestas.</p>

        <p>Quisque ut justo a dolor auctor fermentum. Nam auctor felis non neque facilisis, id fringilla dolor feugiat. Sed in justo vel nulla dapibus gravida. Curabitur auctor turpis sit amet arcu sodales, nec dignissim velit gravida. Nam non sem sem. In hac habitasse platea dictumst. In interdum velit eget sapien pharetra, a tempor erat egestas. Maecenas non felis sit amet justo pretium blandit. Phasellus in vestibulum nulla, eget sollicitudin odio. Vivamus tristique libero sit amet massa condimentum, ac scelerisque dolor fermentum. Nunc id arcu nec lectus tincidunt dictum. Vestibulum vel sem vel nunc hendrerit fermentum. Pellentesque at nisl leo. Quisque accumsan ex in ultricies venenatis. Curabitur aliquam quam a enim efficitur, in eleifend turpis tristique.</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer nec libero nec justo tempor tincidunt. Aenean dignissim leo eget dui malesuada, id euismod odio sodales. Cras in libero eu ex pellentesque egestas. Nunc vehicula, mauris ac egestas faucibus, metus metus malesuada urna, non volutpat ex libero nec risus. Phasellus eu purus ut lorem tincidunt porttitor at sit amet sem. Fusce at tortor dignissim, pharetra urna vel, fermentum mauris. In dapibus magna sit amet urna viverra, vel viverra sem luctus. Donec id velit nec odio sodales euismod. In bibendum ligula sit amet eros aliquet, quis fermentum dui tincidunt. Curabitur at justo vitae libero malesuada aliquet.</p>

        <p>Mauris ut neque sed nisl laoreet pharetra. Vivamus malesuada lacus nec magna vehicula, nec posuere elit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus augue non feugiat efficitur. Cras laoreet orci nec tortor ultricies, in luctus turpis scelerisque. Etiam gravida elit a justo dictum, et convallis ligula facilisis. Nulla vestibulum enim ut elit suscipit, in consectetur eros facilisis. Nulla dapibus mauris sed mi lobortis, in congue justo vestibulum. Donec scelerisque, augue sit amet varius dignissim, nisi dolor tempus orci, ac posuere mauris turpis id justo. Nam eu eros at lorem rhoncus tincidunt. Donec interdum, libero at viverra lobortis, lacus felis sagittis risus, vel cursus quam sapien ac nunc. Duis feugiat, sapien eu tempor vehicula, tortor elit dignissim turpis, sit amet pretium sapien purus eu ex. Ut facilisis consectetur augue, ut vulputate felis egestas vel. Suspendisse condimentum malesuada dui nec feugiat. Aliquam erat volutpat.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor malesuada felis, ut euismod nulla dictum nec. Proin lacinia metus vitae felis ullamcorper, nec dapibus lacus ultricies. Morbi vehicula turpis eu augue consectetur, at ultricies orci sollicitudin. Nullam a justo non turpis vestibulum eleifend at et dui. Curabitur malesuada nibh a ante fringilla, non cursus nisl vehicula. Ut at lacus elit. Etiam id urna a urna ultricies posuere. Suspendisse vehicula urna vel enim blandit, sed ullamcorper eros faucibus. Donec sollicitudin, sapien in interdum venenatis, tortor justo malesuada justo, sed tincidunt dolor odio et nunc. Vivamus in suscipit nulla. Donec at arcu vitae nulla bibendum varius. Vestibulum vel vehicula nisl. Phasellus at urna vel purus vestibulum vulputate. Integer accumsan orci eu metus fermentum, vel consectetur lectus bibendum. Nulla vel lacus in libero vehicula blandit id a sapien.</p>

        <p>Mauris luctus metus ac ligula consequat, at iaculis risus volutpat. Aliquam convallis magna at ex interdum, ac tempor nulla interdum. Nullam lacinia ex a lacus blandit, vel luctus magna pellentesque. Vestibulum vitae lacinia mi. Fusce rutrum ligula non elit porttitor, id scelerisque lacus dignissim. Nulla facilisi. Sed non velit nec nisl dignissim feugiat in non felis. Nullam at erat vel libero gravida viverra. Proin accumsan sapien nec sapien pharetra lacinia. Vestibulum in nisi auctor, ultricies justo vel, luctus libero. Nam ut dapibus leo. Cras dapibus, lacus sed pharetra vehicula, sem purus egestas lacus, ac interdum augue ipsum a justo. Sed vitae justo non nisl varius egestas.</p>

        <p>Quisque ut justo a dolor auctor fermentum. Nam auctor felis non neque facilisis, id fringilla dolor feugiat. Sed in justo vel nulla dapibus gravida. Curabitur auctor turpis sit amet arcu sodales, nec dignissim velit gravida. Nam non sem sem. In hac habitasse platea dictumst. In interdum velit eget sapien pharetra, a tempor erat egestas. Maecenas non felis sit amet justo pretium blandit. Phasellus in vestibulum nulla, eget sollicitudin odio. Vivamus tristique libero sit amet massa condimentum, ac scelerisque dolor fermentum. Nunc id arcu nec lectus tincidunt dictum. Vestibulum vel sem vel nunc hendrerit fermentum. Pellentesque at nisl leo. Quisque accumsan ex in ultricies venenatis. Curabitur aliquam quam a enim efficitur, in eleifend turpis tristique.</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer nec libero nec justo tempor tincidunt. Aenean dignissim leo eget dui malesuada, id euismod odio sodales. Cras in libero eu ex pellentesque egestas. Nunc vehicula, mauris ac egestas faucibus, metus metus malesuada urna, non volutpat ex libero nec risus. Phasellus eu purus ut lorem tincidunt porttitor at sit amet sem. Fusce at tortor dignissim, pharetra urna vel, fermentum mauris. In dapibus magna sit amet urna viverra, vel viverra sem luctus. Donec id velit nec odio sodales euismod. In bibendum ligula sit amet eros aliquet, quis fermentum dui tincidunt. Curabitur at justo vitae libero malesuada aliquet.</p>

        <p>Mauris ut neque sed nisl laoreet pharetra. Vivamus malesuada lacus nec magna vehicula, nec posuere elit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus augue non feugiat efficitur. Cras laoreet orci nec tortor ultricies, in luctus turpis scelerisque. Etiam gravida elit a justo dictum, et convallis ligula facilisis. Nulla vestibulum enim ut elit suscipit, in consectetur eros facilisis. Nulla dapibus mauris sed mi lobortis, in congue justo vestibulum. Donec scelerisque, augue sit amet varius dignissim, nisi dolor tempus orci, ac posuere mauris turpis id justo. Nam eu eros at lorem rhoncus tincidunt. Donec interdum, libero at viverra lobortis, lacus felis sagittis risus, vel cursus quam sapien ac nunc. Duis feugiat, sapien eu tempor vehicula, tortor elit dignissim turpis, sit amet pretium sapien purus eu ex. Ut facilisis consectetur augue, ut vulputate felis egestas vel. Suspendisse condimentum malesuada dui nec feugiat. Aliquam erat volutpat.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor malesuada felis, ut euismod nulla dictum nec. Proin lacinia metus vitae felis ullamcorper, nec dapibus lacus ultricies. Morbi vehicula turpis eu augue consectetur, at ultricies orci sollicitudin. Nullam a justo non turpis vestibulum eleifend at et dui. Curabitur malesuada nibh a ante fringilla, non cursus nisl vehicula. Ut at lacus elit. Etiam id urna a urna ultricies posuere. Suspendisse vehicula urna vel enim blandit, sed ullamcorper eros faucibus. Donec sollicitudin, sapien in interdum venenatis, tortor justo malesuada justo, sed tincidunt dolor odio et nunc. Vivamus in suscipit nulla. Donec at arcu vitae nulla bibendum varius. Vestibulum vel vehicula nisl. Phasellus at urna vel purus vestibulum vulputate. Integer accumsan orci eu metus fermentum, vel consectetur lectus bibendum. Nulla vel lacus in libero vehicula blandit id a sapien.</p>

        <p>Mauris luctus metus ac ligula consequat, at iaculis risus volutpat. Aliquam convallis magna at ex interdum, ac tempor nulla interdum. Nullam lacinia ex a lacus blandit, vel luctus magna pellentesque. Vestibulum vitae lacinia mi. Fusce rutrum ligula non elit porttitor, id scelerisque lacus dignissim. Nulla facilisi. Sed non velit nec nisl dignissim feugiat in non felis. Nullam at erat vel libero gravida viverra. Proin accumsan sapien nec sapien pharetra lacinia. Vestibulum in nisi auctor, ultricies justo vel, luctus libero. Nam ut dapibus leo. Cras dapibus, lacus sed pharetra vehicula, sem purus egestas lacus, ac interdum augue ipsum a justo. Sed vitae justo non nisl varius egestas.</p>

        <p>Quisque ut justo a dolor auctor fermentum. Nam auctor felis non neque facilisis, id fringilla dolor feugiat. Sed in justo vel nulla dapibus gravida. Curabitur auctor turpis sit amet arcu sodales, nec dignissim velit gravida. Nam non sem sem. In hac habitasse platea dictumst. In interdum velit eget sapien pharetra, a tempor erat egestas. Maecenas non felis sit amet justo pretium blandit. Phasellus in vestibulum nulla, eget sollicitudin odio. Vivamus tristique libero sit amet massa condimentum, ac scelerisque dolor fermentum. Nunc id arcu nec lectus tincidunt dictum. Vestibulum vel sem vel nunc hendrerit fermentum. Pellentesque at nisl leo. Quisque accumsan ex in ultricies venenatis. Curabitur aliquam quam a enim efficitur, in eleifend turpis tristique.</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer nec libero nec justo tempor tincidunt. Aenean dignissim leo eget dui malesuada, id euismod odio sodales. Cras in libero eu ex pellentesque egestas. Nunc vehicula, mauris ac egestas faucibus, metus metus malesuada urna, non volutpat ex libero nec risus. Phasellus eu purus ut lorem tincidunt porttitor at sit amet sem. Fusce at tortor dignissim, pharetra urna vel, fermentum mauris. In dapibus magna sit amet urna viverra, vel viverra sem luctus. Donec id velit nec odio sodales euismod. In bibendum ligula sit amet eros aliquet, quis fermentum dui tincidunt. Curabitur at justo vitae libero malesuada aliquet.</p>

        <p>Mauris ut neque sed nisl laoreet pharetra. Vivamus malesuada lacus nec magna vehicula, nec posuere elit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus augue non feugiat efficitur. Cras laoreet orci nec tortor ultricies, in luctus turpis scelerisque. Etiam gravida elit a justo dictum, et convallis ligula facilisis. Nulla vestibulum enim ut elit suscipit, in consectetur eros facilisis. Nulla dapibus mauris sed mi lobortis, in congue justo vestibulum. Donec scelerisque, augue sit amet varius dignissim, nisi dolor tempus orci, ac posuere mauris turpis id justo. Nam eu eros at lorem rhoncus tincidunt. Donec interdum, libero at viverra lobortis, lacus felis sagittis risus, vel cursus quam sapien ac nunc. Duis feugiat, sapien eu tempor vehicula, tortor elit dignissim turpis, sit amet pretium sapien purus eu ex. Ut facilisis consectetur augue, ut vulputate felis egestas vel. Suspendisse condimentum malesuada dui nec feugiat. Aliquam erat volutpat.</p>
      </div>
    </div>
  );
}